name: africa
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - deepspeed
    - accelerate
    - sentencepiece
    - git+https://github.com/huggingface/transformers.git
    - datasets